/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NoteContentType } from './NoteContentType';
import {
    NoteContentTypeFromJSON,
    NoteContentTypeFromJSONTyped,
    NoteContentTypeToJSON,
    NoteContentTypeToJSONTyped,
} from './NoteContentType';

/**
 * Pydantic model for note creation request
 * @export
 * @interface NoteCreate
 */
export interface NoteCreate {
    /**
     * 
     * @type {string}
     * @memberof NoteCreate
     */
    content: string;
    /**
     * 
     * @type {NoteContentType}
     * @memberof NoteCreate
     */
    contentType: NoteContentType;
    /**
     * 
     * @type {string}
     * @memberof NoteCreate
     */
    topicId?: string | null;
}



/**
 * Check if a given object implements the NoteCreate interface.
 */
export function instanceOfNoteCreate(value: object): value is NoteCreate {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    return true;
}

export function NoteCreateFromJSON(json: any): NoteCreate {
    return NoteCreateFromJSONTyped(json, false);
}

export function NoteCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'contentType': NoteContentTypeFromJSON(json['content_type']),
        'topicId': json['topic_id'] == null ? undefined : json['topic_id'],
    };
}

export function NoteCreateToJSON(json: any): NoteCreate {
    return NoteCreateToJSONTyped(json, false);
}

export function NoteCreateToJSONTyped(value?: NoteCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'content_type': NoteContentTypeToJSON(value['contentType']),
        'topic_id': value['topicId'],
    };
}

