/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pydantic model for topic response
 * @export
 * @interface TopicResponse
 */
export interface TopicResponse {
    /**
     * 
     * @type {string}
     * @memberof TopicResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TopicResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof TopicResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the TopicResponse interface.
 */
export function instanceOfTopicResponse(value: object): value is TopicResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function TopicResponseFromJSON(json: any): TopicResponse {
    return TopicResponseFromJSONTyped(json, false);
}

export function TopicResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function TopicResponseToJSON(json: any): TopicResponse {
    return TopicResponseToJSONTyped(json, false);
}

export function TopicResponseToJSONTyped(value?: TopicResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

