/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pydantic model for topic creation request
 * @export
 * @interface TopicCreate
 */
export interface TopicCreate {
    /**
     * 
     * @type {string}
     * @memberof TopicCreate
     */
    name: string;
}

/**
 * Check if a given object implements the TopicCreate interface.
 */
export function instanceOfTopicCreate(value: object): value is TopicCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TopicCreateFromJSON(json: any): TopicCreate {
    return TopicCreateFromJSONTyped(json, false);
}

export function TopicCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function TopicCreateToJSON(json: any): TopicCreate {
    return TopicCreateToJSONTyped(json, false);
}

export function TopicCreateToJSONTyped(value?: TopicCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

